# Generated by Django 4.0.3 on 2023-03-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_location_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
